version: "3"

services:
  # mathapp:
  #   build:
  #     context: MathApp/
  #     dockerfile: Dockerfile
  #     args:
  #       USER_ID: 1000
  #       GROUP_ID: 1000

  #   working_dir: /go/src/mathapp

  #   # command: bee run

  #   ports:
  #     - 8010:8010

  #   networks:
  #     - auth_network

    oauth_provider:
        build:
            context: OAUTH_provider/
            dockerfile: Dockerfile
        # restart: always
        hostname: 'oauth_provider'
        # stop container from exiting(0) after running @COMMAND
        environment:
            - MYSQL_DATABASE='db'
            # So you don't have to use root, but you can if you like
            - MYSQL_USER='user'
            - MYSQL_PASSWORD='password'
            # Password for root access
            - MYSQL_ROOT_PASSWORD='root'
        ports:
            - '80:80'
        volumes:
            - './OAUTH_provider/db.sql:/var/www/html/db.sql'
            - './OAUTH_provider/config/nginx:/etc/nginx/conf.d'

        networks:
            - auth_network
        command: >
            bash -c " 
            usermod -d /var/lib/mysql/ mysql
            && service mysql start
            && mysql -u root -proot < db.sql
            && service php7.2-fpm start
            && service nginx start
            && git clone https://github.com/bshaffer/oauth2-server-php.git -b master
            && tail -f /dev/null"

    auth_server:
        build:
            context: auth_server/
            dockerfile: Dockerfile
            args:
                USER_ID: 1000
                GROUP_ID: 1000
        restart: always
        hostname: 'auth_server'
        ports:
            - "3000:3000"
        networks:
            - auth_network
        links: 
            - oauth_provider
        depends_on: 
            - oauth_provider
        command: /go/src/auth_server/main

    client:
        build:
            context: client/
            dockerfile: Dockerfile
            args:
                USER_ID: 1000
                GROUP_ID: 1000
        restart: always
        ports:
            - "8080:8080"
        hostname: 'client'
        links:
            - auth_server
        depends_on:
            - auth_server
        networks:
            - auth_network
        command: /go/src/client/main

networks:
  auth_network:
    driver: bridge
    external: false
