version: "3"

services:
  auth_server:
    build: auth_server/

    command: python ./server.py

    ports:
      - 1234:1234
    
    networks:
      - auth_network

  client:
    build: client/

    command: python ./client.py

    links:
      - auth_server

    depends_on:
      - auth_server
    
    networks:
      - auth_network
  
networks:
  auth_network:
    driver: bridge
    external: false
