version: "3"

services:
  # mathapp:
  #   build:
  #     context: MathApp/
  #     dockerfile: Dockerfile
  #     args:
  #       USER_ID: 1000
  #       GROUP_ID: 1000

  #   working_dir: /go/src/mathapp

  #   # command: bee run

  #   ports:
  #     - 8010:8010

  #   networks:
  #     - auth_network


    auth_server:
        build:
            context: auth_server/
            dockerfile: Dockerfile
            args:
                USER_ID: 1000
                GROUP_ID: 1000
        restart: always
        hostname: 'auth_server'
        ports:
            - "3000:3000"
        networks:
            - auth_network
        command: /go/src/auth_server/main

    client:
        build:
            context: client/
            dockerfile: Dockerfile
            args:
                USER_ID: 1000
                GROUP_ID: 1000
        restart: always
        ports:
            - "8080:8080"
        hostname: 'client'
        links:
            - auth_server
        depends_on:
            - auth_server
        networks:
            - auth_network
        command: /go/src/client/main

networks:
  auth_network:
    driver: bridge
    external: false
